# -*- coding: utf-8 -*-
"""Vision.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15xTVdXwEh6KNaulo0nCQRUKhtr1H8iet

# Project Vision Initial Build

Importing Libraries
"""

# ===== Libs for Gemini ===== #
from PIL import Image
import textwrap
from IPython.display import Markdown
import google.generativeai as genai
from google.colab import userdata

# ===== Libs for Text to Speech ===== #
# !pip install gTTS
from gtts import gTTS
from IPython.display import Audio

# ===== Libs for Audio Speed Control ===== #
# !pip install pydub
from pydub import AudioSegment

# ===== Libs for Text to G-Drive Mapping ===== #
from google.colab import drive
import os

# ===== Function for Markdown ===== #
def to_markdown(text):
  text= text.replace('*',  '  *')
  return Markdown(textwrap.indent(text, '> ',
                                  predicate=lambda _: True))
# ===== Setting ModelConfigs ===== #
genai.configure(api_key=userdata.get('Gemini_API_Key'))
model = genai.GenerativeModel('gemini-1.5-flash')

# ===== Main Function ===== #
def main(image, prompt,max_words,playback_speed_input):
  response = model.generate_content([prompt,
                                   img],
                                  stream = True)

  response.resolve()
  output_string = response.text#.split("image:")[1]
  to_markdown(output_string)
  tts = gTTS(output_string, slow =  False)
  tts.save('output.mp3')
  sound_file = 'output.mp3'

  audio = AudioSegment.from_mp3("output.mp3")
  final_output = audio.speedup(playback_speed = playback_speed_input)
  final_output.export("output.mp3", format="mp3")
  print(output_string)
  return  Audio(sound_file, autoplay=True,rate=2)



# ===== Mounting G-Drive for Image input ===== #
drive.mount('/content/drive')

folder_path = "/content/drive/MyDrive/Project Vision/Vision Input"
os.chdir(folder_path)  # Change working directory
print("Current Directory:", os.getcwd())

files = [os.path.join(folder_path, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]
# Sort files by modification time
files.sort(key=os.path.getmtime)
last_input = files[0]

# ===== Prompt Hyper Params ===== #
playback_speed_input = 1.25
max_words = 50
prompt = 'Generate a description of the image in'+ str(max_words) + 'words as if you are narrating the user what he is seeing in realtime'

# ===== Running Main if atleast one filepresentt then running the latest uploaded one.  But would be deleting all files aster running ===== #
if  len(files) > 0:
  print(len(files))
  img = Image.open(last_input)
  output = main(img,prompt,max_words,playback_speed_input)
  if os.path.exists(last_input):
    os.remove(last_input)
    os.remove(folder_path + '/output.mp3')
output